/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.arg.arg_factory;

import aermicioi.aedi_property_reader.core.convertor_factory;
import aermicioi.aedi_property_reader.helper.help_decorating_exception;
import aermicioi.aedi.storage.locator;

/**
Convertor Factory for command line arguments.

Params:
	FromType = original representation form of data to be converted.
	ToType = type of component that is built based on FromType data.
**/
class GetoptConvertorFactory(To, From : string = string) : ConvertorFactory!(From, To) {

    private {
        string identity_;
        string[] args;
        Locator!() locator_;
    }

    public {
        /**
        Default constructor for GetoptConvertorFactory!(To, From)
        **/
        this() {
            import core.runtime;
            this(Runtime.args());
        }

        /**
        Constructor for GetoptConvertorFactory!(To, From)

        Params:
            args = source from which constructor creates component.
        **/
        this(string[] args) {
            this.args = args;
        }

        @property {

            /**
            Set convertible.

            Params:
            	identity = the value to be set
            Returns:
            	GetoptConvertorFactory!(To, From)
            **/
            GetoptConvertorFactory!(To, From) convertible(string identity) @safe nothrow {
            	this.identity_ = identity;

            	return this;
            }

            /**
            Get convertible

            Returns:
            	string
            **/
            string convertible() @safe nothrow {
            	return this.identity_;
            }

            /**
            Set locator.

            Params:
            	locator = the value to be set
            Returns:
            	Locator!()
            **/
            GetoptConvertorFactory!(To, From) locator(Locator!() locator) @safe nothrow {
            	this.locator_ = locator;

            	return this;
            }

            /**
            Get the type info of To that is created.

    		Returns:
    			TypeInfo object of created object.
    		**/
            TypeInfo type() {
                return typeid(To);
            }
        }

        /**
		Instantiates component of type To.

		Returns:
			To instantiated data of type To.
		**/
        To factory() {
            import std.getopt;
            import std.conv : ConvException;
            import aermicioi.aedi_property_reader.core.exception;

            To value;
            string[] args = this.args;

            try {

                auto help = getopt(args, std.getopt.config.passThrough, this.convertible, &value);

                if (help.helpWanted) {
                    throw new HelpDecoratingException("help needed");
                }
            } catch (ConvException e) {

                throw new ConvertorException("Failed to convert property due to " ~ e.msg, e);
            } catch (GetOptException e) {

                throw new ConvertorException("Failed to convert property due to " ~ e.msg, e);
            }

            return value;
        }
    }
}
