/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.xml.xml_container;

import aermicioi.aedi;
import aermicioi.aedi_property_reader.xml.xml_factory;
import aermicioi.aedi_property_reader.core.generic_convertor_container;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi_property_reader.xml.accessor;
import aermicioi.aedi_property_reader.core.accessor;
import std.xml;
import std.range;
import std.typecons;
import std.conv;

/**
Xml document data source/locator used by converting containers.
**/
class XmlLocator : Locator!(XmlElement) {

    private {
        XmlElement xml_;
		PropertyAccessor!XmlElement accessor;
    }

    public {

		/**
		Default constructor for XmlLocator
		**/
		this(PropertyAccessor!XmlElement accessor) {
			this.accessor = accessor;
			this.xml = XmlElement(new Document("<root></root>"));
		}

        @property {


			/**
			Set xml

			Params:
				xml = xml document used as source of data

			Returns:
				typeof(this)
			**/
        	XmlLocator xml(XmlElement xml) @safe nothrow
			in {
				assert(xml.kind == XmlElement.Kind.element);
			}
			body {
        		this.xml_ = xml;

        		return this;
        	}

			/**
			Get xml

			Returns:
				XmlElement
			**/
        	XmlElement xml() @safe nothrow {
        		return this.xml_;
        	}
        }

        /**
		Get a xml element that is accessable from root element.

		Params:
			path = the element id.

		Throws:
			NotFoundException in case if the element wasn't found.

		Returns:
			XmlElement child element if it is available.
		**/
        XmlElement get(string path) {
            if (this.accessor.has(this.xml, path)) {
				return this.accessor.access(this.xml, path);
			}

			throw new NotFoundException(text("Could not find ", path, " in xml document"));
        }

        /**
        Check if a xml element is present in xml by key.

        Params:
        	path = identity of element.

    	Returns:
    		bool true if an element by key is present in Locator.
        **/
        bool has(in string path) inout {
			return this.accessor.has(this.xml_, path);
        }
    }
}

/**
Generic convertor container version for xml documents.
**/
alias XmlConvertorContainer = GenericConvertorContainer!(XmlElement, XmlConvertorFactory);