/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.xml.xml_container;

import aermicioi.aedi;
import aermicioi.aedi_property_reader.xml.xml_factory;
import aermicioi.aedi_property_reader.core.generic_convertor_container;
import aermicioi.aedi.storage.locator;
import std.xml;
import std.range;
import std.typecons;

/**
Xml document data source/locator used by converting containers.
**/
class XmlLocator : Locator!(Element) {
    
    private {
        Element xml_;
    }
    
    public {

		/**
		Default constructor for XmlLocator
		**/
		this() {
			this.xml = new Document("<a></a>");
		}
        
        @property {
			/**
			Set xml
			
			Params: 
				xml = xml document used as source of data
			
			Returns:
				typeof(this)
			**/
        	XmlLocator xml(Element xml) @safe nothrow {
        		this.xml_ = xml;
        	
        		return this;
        	}
        	
			/**
			Get xml
			
			Returns:
				Element
			**/
        	Element xml() @safe nothrow {
        		return this.xml_;
        	}
        }
        
        /**
		Get a xml element that is accessable from root element.
		
		Params:
			path = the element id.
			
		Throws:
			NotFoundException in case if the element wasn't found.
		
		Returns:
			Element child element if it is available.
		**/
        Element get(string path) {
            import std.algorithm : map, splitter, joiner, endsWith;
			import std.conv : to, ConvException;
			Element current = this.xml_;
			auto segments = path.splitter(".").map!(a => a.splitter("[")).joiner;
			foreach (segment; segments) {
				
				if (segment.endsWith("]")) {
					try {
						size_t index = segment[0 .. $ - 1].to!size_t;
						if (index >= current.elements.length) {
						
							throw new NotFoundException("Could not find child xml node identified by " ~ path ~ " in root xml");
						}

						current = current.elements[index];
						continue;
					} catch (ConvException e) {
						segment = segment[1 .. $ - 2]; // take out quotes and extra ending ]
					}
				}

				bool found = false;
				foreach (element; current.elements) {
					if (element.tag.name == segment) {
						found = true;
						current = element;
					}
				}

				if (!found) {
					throw new NotFoundException("Could not find child xml node identified by " ~ path ~ " in root xml");
				}
			}
            
            return current;
        }
        
        /**
        Check if a xml element is present in xml by key.
        
        Params:
        	path = identity of element.
        	
    	Returns:
    		bool true if an element by key is present in Locator.
        **/
        bool has(in string path) inout {
			import std.algorithm;
			import std.conv;
			Element current = cast() this.xml_;
			auto segments = path.splitter(".").map!(a => a.splitter("[")).joiner;
			foreach (segment; segments) {
				
				if (segment.endsWith("]")) {
					try {
						size_t index = segment[0 .. $ - 1].to!size_t;
						if (index >= current.elements.length) {
							return false;
						}

						current = current.elements[index];
						continue;
					} catch (ConvException e) {
						segment = segment[1 .. $ - 2]; // take out quotes and extra ending ]
					}
				}

				bool found = false;
				foreach (element; current.elements) {
					if (element.tag.name == segment) {
						found = true;
						current = element;
					}
				}

				if (!found) {
					return false;
				}
			}

			return true;
        }
    }
}

/**
Generic convertor container version for xml documents.
**/
alias XmlConvertorContainer = GenericConvertorContainer!(Element, XmlConvertorFactory);