/**
License:
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

Authors:
    Alexandru Ermicioi
**/
module aermicioi.aedi_property_reader.json.setter;

import aermicioi.aedi.configurer.annotation.annotation;
import aermicioi.aedi_property_reader.convertor.setter;
import aermicioi.aedi_property_reader.convertor.exception;
import std.json;
import std.exception;
import std.conv : text;
import std.experimental.allocator;

@component
class JsonObjectSetter : PropertySetter!(JSONValue, JSONValue) {

    /**
    Set a field or property of CompositeType.

    Params:
        composite = composite that will store value
        value = actual value that is assigned to a field in composite
        property = the identity of field in composite
    Throws:
        InvalidArgumentException when value or composite is not what was expected
    **/
    void set(ref JSONValue composite, JSONValue value, string property, RCIAllocator allocator = theAllocator) const {
        enforce!ConvertorException(composite.type == JSON_TYPE.object, text("The passed json is not of object type but ", composite.type));

        composite.object["property"] = value;
    }

    /**
     Identify the type of supported component.

     Identify the type of supported component. It returns type info of component
     if it is supported by accessor, otherwise it will return typeid(void) denoting that
     the type isn't supported by accessor. The accessor is not limited to returning the type
     info of passed component, it can actually return type info of super type or any type
     given the returned type is implicitly convertible or castable to ComponentType.

     Params:
         component = the component for which accessor should identify the underlying type

     Returns:
         TypeInfo type information about passed component, or typeid(void) if component is not supported.
     **/
    TypeInfo componentType(ref JSONValue composite) const nothrow {
        return typeid(JSONValue);
    }
}

@component
class JsonArraySetter : PropertySetter!(JSONValue, JSONValue, size_t) {

    /**
    Set a field or property of CompositeType.

    Params:
        composite = composite that will store value
        value = actual value that is assigned to a field in composite
        property = the identity of field in composite
    Throws:
        InvalidArgumentException when value or composite is not what was expected
    **/
    void set(ref JSONValue composite, JSONValue value, size_t property, RCIAllocator allocator = theAllocator) const {
        enforce!ConvertorException(composite.type == JSON_TYPE.ARRAY, text("The passed json is not of array type but ", composite.type));

        if (composite.array.length <= property) {
            composite.array.length = property + 1;
        }

        composite.array[property] = value;
    }

    /**
     Identify the type of supported component.

     Identify the type of supported component. It returns type info of component
     if it is supported by accessor, otherwise it will return typeid(void) denoting that
     the type isn't supported by accessor. The accessor is not limited to returning the type
     info of passed component, it can actually return type info of super type or any type
     given the returned type is implicitly convertible or castable to ComponentType.

     Params:
         component = the component for which accessor should identify the underlying type

     Returns:
         TypeInfo type information about passed component, or typeid(void) if component is not supported.
     **/
    TypeInfo componentType(ref JSONValue composite) const nothrow {
        return typeid(JSONValue);
    }
}