/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.convertor_configurer;

import aermicioi.aedi.storage.storage;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi_property_reader.convertor_factory;
import aermicioi.aedi_property_reader.convertor_container;
import aermicioi.aedi_property_reader.generic_convertor_factory;
import aermicioi.aedi_property_reader.generic_convertor_container;
import aermicioi.aedi_property_reader.env;
import aermicioi.aedi_property_reader.arg;
import aermicioi.aedi_property_reader.json;
import aermicioi.aedi_property_reader.xml;
import std.json;
import std.xml;

struct ConvertorContext(T : Storage!(ConvertorFactory!(FromType, Object), string), FromType) {
    
    public {
        T container;
        
        static if (is(T : GenericConvertorContainer!(FromType, DefaultFactory), alias DefaultFactory)) {
            auto property(ToType)(string path) {
                import std.traits;
                
                return this.property!(DefaultFactory!(ToType, FromType), ToType)(path);
            }
        }
        
        auto property(Factory : ConvertorFactory!(FromType, ToType), ToType)(string path) {
            
            auto implementation = new Factory;
            auto wrapper = new GenericObjectWrappingConvertorFactory!(Factory!(ToType, FromType))(implementation);
            
            container.set(wrapper, path);
            
            return implementation;
        }
    }
}

auto configure(T : Storage!(ConvertorFactory!(FromType, Object), string), FromType)(T container) {
    return ConvertorContext!(T, FromType)(container);
}

auto environment() {
    return environment(new EnvironmentLocator());
}

auto environment(Locator!(string, string) locator) {
    auto container = new EnvironmentConvertorContainer;
    container.locator = locator;
    
    return container;
}

auto argument() {
    return argument(new GetoptIdentityLocator());
}

auto argument(Locator!(string, string) locator) {
    auto container = new GetoptConvertorContainer;
    container.locator = locator;
    
    return container;
}

auto json() {
    return json(new JsonLocator());
}

auto json(Locator!(JSONValue, string) locator) {
    auto container = new JsonConvertorContainer();
    container.locator = locator;
    
    return container;
}

auto xml() {
    return xml(new XmlLocator);
}

auto xml(Locator!(Element, string) locator) {
    auto container = new XmlConvertorContainer;
    container.locator = locator;
    
    return container;
}