/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.generic_convertor_factory;

import aermicioi.aedi.storage.decorator;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi.storage.wrapper;
import aermicioi.aedi_property_reader.convertor_factory;

/**
A factory that wraps any convertor factory into an interface that is compliant with generic convertor container, and rest of aedi containers.
**/
class GenericObjectWrappingConvertorFactory(T : ConvertorFactory!(FromType, ToType), FromType, ToType) : 
	ConvertorFactory!(FromType, Object), MutableDecorator!T {
    
    private {
        T decorated_;
    }
    
    public {
        
		/**
		Constructor for GenericObjectWrappingConvertorFactory!(T, FromType, ToType)
		
		Params: 
			factory = wrapped factory
		**/
        this(T factory) {
            this.decorated = factory;
        }
        
        @property {
			/**
			Set decorated
			
			Params: 
				decorated = factory that is wrapped
			
			Returns:
				typeof(this)
			**/
            GenericObjectWrappingConvertorFactory!T decorated(T decorated) @safe nothrow {
            	this.decorated_ = decorated;
            
            	return this;
            }
            
			/**
			Get decorated
			
			Returns:
				T
			**/
            T decorated() @safe nothrow {
            	return this.decorated_;
            }
            
			/**
			Set convertible
			
			Params: 
				convertible = data that the factory should convert into ToType component
			Returns:
				ConvertorFactory!(FromType, ToType)
			**/
        	GenericObjectWrappingConvertorFactory!T convertible(FromType convertible) @safe nothrow {
        		this.decorated.convertible = convertible;
        	
        		return this;
        	}
        	
			/**
			Get convertible data
			
			Returns:
				FromType
			**/
        	FromType convertible() @safe nothrow {
        		return this.decorated.convertible;
        	}
        	
			/**
    		Get the type info of T that is created.
    		
    		Returns:
    			TypeInfo object of created component.
    		**/
        	TypeInfo type() {
        	    return decorated.type;
        	}
        	
			/**
			Set a locator to object.
			
			Params:
				locator = the locator that is set to oject.
			
			Returns:
				GenericObjectWrappingConvertorFactory!T
			**/
        	GenericObjectWrappingConvertorFactory!T locator(Locator!() locator) {
        		this.decorated.locator = locator;
        	
        		return this;
        	}
        }
        
		/**
		Instantiates component of type T.
		
		Returns:
			T instantiated component.
		**/
        Object factory() {
            
            static if (is(ToType : Object)) {
                return this.decorated.factory;
            } else {
                
                return new WrapperImpl!ToType(this.decorated.factory);
            }
            
        }
    }
}