/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.core.core;

import aermicioi.aedi.storage.storage;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi_property_reader.convertor.convertor;
import aermicioi.aedi_property_reader.convertor.chaining_convertor;
import aermicioi.aedi_property_reader.convertor.type_guesser;
import aermicioi.aedi_property_reader.convertor.mapper;
import aermicioi.aedi_property_reader.core.document :
	DocumentContainerImpl = DocumentContainer,
	WithConvertorBuilder,
	WithConvertorsFor,
	WithConvertorSources,
	WithConvertors;
import std.meta;
import std.traits;
import std.experimental.logger;
import std.exception;

/**
Configuration context for a property
**/
struct PropertyContext(Type, DocumentContainer) {
	string path;
	Convertor[] convertors;
	DocumentContainer container;
	Locator!() locator;
}

/**
Configuration context that is providing a nice api to add convertors into a container for a document.
**/
struct DocumentContainerBuilder
	(DocumentContainer : DocumentContainerImpl!(DocumentType, FieldType), ConvertorBuilder, DocumentType, FieldType)
	if (is(DocumentContainer : Storage!(Convertor, string))) {

	/**
	Builder used to constructo convertors for configured properties.
	**/
	ConvertorBuilder builder;

	/**
	Configured container.
	**/
    DocumentContainer container;

	/**
	Locator useable in registering properties.
	**/
	Locator!() locator;

	/**
	Constructor for DocumentContainerBuilder

	Params:
		container = to configure
		builder = convertor builder used to create convertors for properties
	**/
	this(DocumentContainer container, ConvertorBuilder builder, CombinedConvertor convertor, Locator!() locator) {
		this.container = container;
		this.builder = builder;
		this.container.convertor = convertor;
		this.locator = locator;

		static if (is(DocumentContainer : WithConvertorsFor!Types, Types...)) {
			static foreach (Type; Types) {
				this.register!(Type, Type);
			}
		}

		static if (is(DocumentContainer : WithConvertors!ConvertorsFactory, alias ConvertorsFactory)) {
			foreach (prebuilt; ConvertorsFactory()) {
				this.register(prebuilt, prebuilt.to.toString);
			}
		}
	}

	/**
	ditto
	**/
    alias container this;

	/**
	Associate a convertor to a field in document that has property path, to be used for conversion.

	Params:
		To = the type of destination component that convertor should yield
		path = property path for a field in document.
	**/
    PropertyContext!(To, DocumentContainer) register(To)(string path) {

		static if (is(DocumentContainer : WithConvertorSources!SourceTypes, SourceTypes...)) {} else {
			alias SourceTypes = AliasSeq!();
		}

		PropertyContext!(To, DocumentContainer) context = PropertyContext!(To, DocumentContainer)(path, null, container, locator);

		debug(trace) trace(
			"Injecting convertor for ",
			path,
			" in document container to convert to ",
			typeid(To),
			" using ",
			builder
		);

		context.convertors ~= this.register(builder.make!(To, FieldType), path).convertors;

		static foreach (From; SourceTypes) {

			debug(trace) trace(
				"Injecting convertor for ",
				typeid(From),
				" in document container to convert to ",
				typeid(To),
				" using ",
				builder
			);

			context.convertors ~= this.register(builder.make!(To, From)).convertors;
		}

		return context;
    }

	/**
	Associate a convertor to a type to be used by document when no specific convertor is provided for document field.

	Params:
		To = the type of destination component that convertor should yield
	**/
    PropertyContext!(To, DocumentContainer) register(To)() {

        return this.register!(To, To);
    }

	/**
	Associate a convertor to a type for an interface to be used by document when no specific convertor is provided for document field.

	Params:
		Iface = interface for which the convertor is bound to.
		To = the type of destination component that convertor should yield
	**/
    PropertyContext!(To, DocumentContainer) register(Iface, To : Iface)() {
        import std.traits : fullyQualifiedName;

        return this.register!To(fullyQualifiedName!Iface);
    }

	/**
	Register convertor for a property on path.

	Params:
		convertor = convertor used to convert value found on path
		path = property path for which convertor could be used

	Returns:
		typeof(this)
	**/
	PropertyContext!(void, DocumentContainer) register(Convertor convertor, string path) {
		this.container.set(convertor, path);

		return PropertyContext!(void, DocumentContainer)(path, [convertor], container, locator);
	}

	/**
	ditto
	**/
	PropertyContext!(void, DocumentContainer) register(Convertor convertor) {
		this.container.set(convertor);

		return PropertyContext!(void, DocumentContainer)(null, [convertor], container, locator);
	}

    alias property = register;
}

/**
Take a document container and create a configuration context for it.

Params:
	container = container for which configuration context is created.
	builder = builder used to construct convertors used by container.
	convertor = convertor used to resolve conversion chain from origin to destination type.
	locator = locator used in registration and construction of properties.

Returns:
	DocumentContainerBuilder(DocumentContainer, AdvisedConvertor, DocumentType, FieldType) a configuration context
**/
auto configure(DocumentContainerType, ConvertorBuilderType)(
	DocumentContainerType container,
	ConvertorBuilderType builder,
	CombinedConvertor convertor = new CombinedConvertorImpl(),
	Locator!() locator = null
) if (!is(ConvertorBuilderType : Locator!())) {
    return DocumentContainerBuilder!(DocumentContainerType, ConvertorBuilderType)(container, builder, convertor, locator);
}

/**
ditto
**/
auto configure(DocumentContainer : WithConvertorBuilder!ConvertorBuilderFactory, alias ConvertorBuilderFactory)(
		DocumentContainer container,
		CombinedConvertor convertor = new CombinedConvertorImpl(),
		Locator!() locator = null
	) {

	return DocumentContainerBuilder!(DocumentContainer, ReturnType!ConvertorBuilderFactory)
		(container, ConvertorBuilderFactory([container]), convertor, locator);
}

/**
ditto
**/
auto configure(DocumentContainer : WithConvertorBuilder!ConvertorBuilderFactory, alias ConvertorBuilderFactory)(
		DocumentContainer container,
		Locator!() locator
	) {

	return DocumentContainerBuilder!(DocumentContainer, ReturnType!ConvertorBuilderFactory)
		(container, ConvertorBuilderFactory([container]), new CombinedConvertorImpl(), locator);
}

/**
Register a description for property.

See:
	Aedi framework $(D_INLINECODE .describe) component configuration method.
**/
Context describe(Context : PropertyContext!(To, DocumentContainer), DocumentContainer, To)(Context context, string title, string description)
	in(context.locator !is null, "Component locator is missing. It is required for proper functioning") {
	import aermicioi.aedi : IdentityDescriber, locate;
	context.locator.locate!(IdentityDescriber!())().register(context.path, title, description);

	return context;
}

/**
Register a default value for property.

Params:
	context = property context
	value = default value for property

Returns:
	Configuration context
**/
Context optional(Context : PropertyContext!(To, DocumentContainer), DocumentContainer, To)(Context context, auto ref To value)
	in(context.locator !is null, "Component locator is missing. It is required for fetching default values storage.") {
	import aermicioi.aedi : ValueContainer, locate, configure;

	with (context.locator.locate!ValueContainer.configure) {
		register(value, context.path);
	}

	return context;
}