/**
License:
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

Authors:
    Alexandru Ermicioi
**/
module aermicioi.aedi_property_reader.core.inspector;

import std.traits;
import std.meta;
import aermicioi.util.traits : isPropertyGetter, isPublic;

interface Inspector(ComponentType, KeyType = string) {

    TypeInfo typeOf(ComponentType component, in KeyType property) const;

    bool has(ComponentType component, in KeyType property) const;

    KeyType[] properties(ComponentType component) const;
}

class AssociativeArrayInspector(ComponentType : Z[KeyType], KeyType = string, Z) : Inspector!(ComponentType, KeyType) {

    TypeInfo typeOf(ComponentType component, in KeyType property) const {
        return typeid(Z);
    }

    bool has(ComponentType component, in KeyType property) const {
        return (property in component) !is null;
    }

    KeyType[] properties(ComponentType component) const {
        import std.array;

        return component.byKey.array;
    }
}

class ArrayInspector(ComponentType : Z[], Z) : Inspector!(ComponentType, size_t) {

    TypeInfo typeOf(ComponentType component, in size_t property) const {
        return typeid(Z);
    }

    bool has(ComponentType component, in size_t property) const {
        return component.length > property;
    }

    size_t[] properties(ComponentType component) const {
        import std.array;
        import std.range;

        return iota(component.length).array;
    }
}

class CompositeInspector(ComponentType) : Inspector!(ComponentType, size_t)
    if (isAggregateType!ComponentType) {

    TypeInfo typeOf(ComponentType component, in string property) const {
        static foreach (member; __traits(allMembers, ComponentType)) {
            static if (isPublic!(ComponentType, member)) {
                alias m = Alias!(__traits(getMember, component, member));
                static if (isField!(ComponentType, member) || (isSomeFunction!m && isPropertyGetter!m)) {
                    if (member == property) {
                        return typeid(typeof(__traits(getMember, component, member)));
                    }
                }
            }
        }
    }

    bool has(ComponentType component, in string property) const {
        import std.algorithm : canFind;
        return this.properties(component).canFind(property);
    }

    string[] properties(ComponentType component) const {
        string[] props;

        static foreach (member; __traits(allMembers, ComponentType)) {
            static if (isPublic!(ComponentType, member)) {
                alias m = Alias!(__traits(getMember, component, member));
                static if (isField!(ComponentType, member) || (isSomeFunction!m && isPropertyGetter!m)) {
                    props ~= member;
                }
            }
        }
    }
}