/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.yaml.convertor;

import aermicioi.aedi.configurer.annotation.annotation;
import aermicioi.aedi_property_reader.convertor.accessor;
import aermicioi.aedi_property_reader.convertor.exception;
import aermicioi.aedi_property_reader.convertor.convertor;
import aermicioi.aedi_property_reader.convertor.placeholder;
import aermicioi.aedi_property_reader.convertor.type_guesser;
import aermicioi.aedi_property_reader.yaml.inspector;
import aermicioi.aedi_property_reader.yaml.yaml;
import dyaml;
import std.conv;
import std.datetime : SysTime;
import std.exception;
import std.experimental.allocator;
import std.meta : AliasSeq;
import std.range;
import std.traits;

@component
class YamlConvertor : Convertor {
	alias ToTypes = AliasSeq!(bool, long, real, ubyte[], string, SysTime, Node[], Node.Pair[]);
	mixin ToMixin!ToTypes;
	mixin FromMixin!Node;
	mixin ConvertsFromToMixin DefaultConvertsImplementation;
	mixin EqualToHashToStringOpCmpMixin;

	private TypeGuesser!Node guesser;

	@autowired
	this(TypeGuesser!Node guesser)
		in (guesser !is null, "Expected yaml type guesser not null.") {
		this.guesser = guesser;
	}

    bool converts(in Object from, const TypeInfo to) @safe const nothrow {
		try {
			if (DefaultConvertsImplementation.converts(from, to)) {
				TypeInfo actual = this.guesser.guess(from.unwrap!Node);

				if (actual is to) {
					return true;
				}

				if (to is typeid(Node[])) {
					return true;
				}

				if (to is typeid(Node.Pair[])) {
					return true;
				}
			}

			return false;
		} catch (Exception e) {
			throw new Error("Unexpected exception occured during check whether convertor is able to convert or not.", e);
		}
    }

    bool converts(in Object from, in Object to) @safe const nothrow {
        return this.converts(from, to.identify);
    }

	/**
    Convert from component to component.

    Params:
        from = original component that is to be converted.
        to = destination object that will be constructed out for original one.
        allocator = optional allocator that could be used to construct to component.
    Throws:
        ConvertorException when there is a converting error
        InvalidArgumentException when arguments passed are not of right type or state
    Returns:
        Resulting converted component.
    **/
    Object convert(in Object from, const TypeInfo to, RCIAllocator allocator = theAllocator) const {
		enforce!ConvertorException(this.converts(from, to), text(
            "Cannot convert ", from.identify, " to ", to, " expected original component of types: ", this.from, " and destination types of ", this.to
        ));

		if (from.unwrap!Node.isInt && (to is typeid(long))) {
			return from.unwrap!Node.get!long.pack(from, this, allocator);
		}

		if (from.unwrap!Node.isFloat && (to is typeid(real))) {
			return from.unwrap!Node.get!real.pack(from, this, allocator);
		}

		if (from.unwrap!Node.isBinary && (to is typeid(ubyte[]))) {
			return from.unwrap!Node.get!(ubyte[]).pack(from, this, allocator);
		}

		if (from.unwrap!Node.isBool && (to is typeid(bool))) {
			return from.unwrap!Node.get!bool.pack(from, this, allocator);
		}

		if (from.unwrap!Node.isString && (to is typeid(string))) {
			return from.unwrap!Node.get!string.pack(from, this, allocator);
		}

		if (from.unwrap!Node.isTime && (to is typeid(SysTime))) {
			return from.unwrap!Node.get!SysTime.pack(from, this, allocator);
		}

		if (to is typeid(Node[])) {
			return from.unwrap!Node.get!(Node[]).pack(from, this, allocator);
		}

		if (to is typeid(Node.Pair[])) {
			return from.unwrap!Node.get!(Node.Pair[]).pack(from, this, allocator);
		}

		assert(false, "Code flow should not get here");
	}

    /**
    Destroy component created using this convertor.

    Destroy component created using this convertor.
    Since convertor could potentially allocate memory for
    converted component, only itself is containing history of allocation,
    and therefore it is responsible as well to destroy and free allocated
    memory with allocator.

    Params:
        converted = component that should be destroyed.
        allocator = allocator used to allocate converted component.
    Return:
        true if component is destroyed, false otherwise
    **/
    void destruct(const TypeInfo from, ref Object converted, RCIAllocator allocator = theAllocator) const {
        enforce!ConvertorException(this.destroys(from, converted), text("Cannot destroy component ", converted.identify, " that is not convertible by ", this));

		static foreach (Type; ToTypes) {
			if (converted.identify is typeid(Type)) {
				converted.unpack!Type(allocator);
			}
		}
	}
}

@component
class YamlNodePairsToAssociativeArrayConvertor : Convertor {
	mixin ToMixin!(Node[Node]);
	mixin FromMixin!(Node.Pair[]);
	mixin ConvertsFromToMixin DefaultConvertsImplementation;
	mixin EqualToHashToStringOpCmpMixin;

	/**
    Convert from component to component.

    Params:
        from = original component that is to be converted.
        to = destination object that will be constructed out for original one.
        allocator = optional allocator that could be used to construct to component.
    Throws:
        ConvertorException when there is a converting error
        InvalidArgumentException when arguments passed are not of right type or state
    Returns:
        Resulting converted component.
    **/
    Object convert(in Object from, const TypeInfo to, RCIAllocator allocator = theAllocator) const {
		enforce!ConvertorException(this.converts(from, to), text(
            "Cannot convert ", from.identify, " to ", to, " expected original component of types: ", this.from, " and destination types of ", this.to
        ));

		Node[Node] container;

		foreach (pair; from.unwrap!(Node.Pair[])) {
			container[pair.key] = pair.value;
		}

		return container.pack(from, this, allocator);
	}

    /**
    Destroy component created using this convertor.

    Destroy component created using this convertor.
    Since convertor could potentially allocate memory for
    converted component, only itself is containing history of allocation,
    and therefore it is responsible as well to destroy and free allocated
    memory with allocator.

    Params:
        converted = component that should be destroyed.
        allocator = allocator used to allocate converted component.
    Return:
        true if component is destroyed, false otherwise
    **/
    void destruct(const TypeInfo from, ref Object converted, RCIAllocator allocator = theAllocator) const {
        enforce!ConvertorException(this.destroys(from, converted), text("Cannot destroy component ", converted.identify, " that is not convertible by ", this));

		converted.unpack!(Node[Node])(allocator);
	}
}