/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module app;

import aermicioi.aedi;
import aermicioi.aedi_property_reader;
import std.stdio;
import std.algorithm;

/**
A struct that should be managed by container.
**/
struct Color {
    ubyte r;
    ubyte g;
    ubyte b;
}

/**
Size of a car.
**/
struct Size {
    
    ulong width;
    ulong height;
    ulong length;
}

/**
Interface for engines.

An engine should implement it, in order to be installable in a car.
**/
interface Engine {
    
    public {
        
        void turnOn();
        void run();
        void turnOff();
    }
}

/**
A concrete implementation of Engine that uses gasoline for propelling.
**/
class GasolineEngine : Engine {
    
    public {
        
        void turnOn() {
            writeln("pururukVrooomVrrr");
            
        }
        
        void run() {
            writeln("vrooom");
        }
        
        void turnOff() {
            writeln("vrrrPrrft");
        }
    }
}

/**
A concrete implementation of Engine that uses diesel for propelling.
**/
class DieselEngine : Engine {
    
    public {
        
        void turnOn() {
            writeln("pururukVruumVrrr");
            
        }
        
        void run() {
            writeln("vruum");
        }
        
        void turnOff() {
            writeln("vrrrPft");
        }
    }
}

/**
A concrete implementation of Engine that uses electricity for propelling.
**/
class ElectricEngine : Engine {
    public {
        
        void turnOn() {
            writeln("pzt");
            
        }
        
        void run() {
            writeln("vvvvvvvvv");
        }
        
        void turnOff() {
            writeln("tzp");
        }
    }
}

/**
Tire, what it can represent else?
**/
class Tire {
    private {
        int size_;
        float pressure_;
        string vendor_;
    }
    
    public @property {
        Tire size(int size) @safe nothrow {
        	this.size_ = size;
        
        	return this;
        }
        
        int size() @safe nothrow {
        	return this.size_;
        }
        
        Tire pressure(float pressure) @safe nothrow {
        	this.pressure_ = pressure;
        
        	return this;
        }
        
        float pressure() @safe nothrow {
        	return this.pressure_;
        }
        
        Tire vendor(string vendor) @safe nothrow {
        	this.vendor_ = vendor;
        
        	return this;
        }
        
        string vendor() @safe nothrow {
        	return this.vendor_;
        }
    }
    
    public override string toString() {
        import std.algorithm;
        import std.range;
        import std.conv;
        import std.utf;
        
        return only("Tire(", this.size.to!string, " inch, ", this.pressure.to!string, " atm, ", this.vendor, ")")
            .joiner
            .byChar
            .array;
    }
}

/**
A class representing a car.
**/
class Car {
    
    private {
        Color color_; // Car color
        Size size_; // Car size
        Engine engine_; // Car engine
        
        Tire frontLeft_;
        Tire frontRight_;
        Tire backLeft_;
        Tire backRight_;
    }
    
    public {
        
        /**
        Constructor of car.
        
        Constructs a car with a set of sizes. A car cannot of course have 
        undefined sizes, so we should provide it during construction.
        
        Params:
            size = size of a car.
        **/
        this(Size size, Engine engine) {
            this.size_ = size;
            this.engine = engine;
        }
        
        @property {
            
            /**
            Set color of car
            
            Set color of car. A car can live with undefined color (physics allow it).
            
            Params:
            	color = color of a car.
            
            Returns:
            	Car
            **/
            Car color(Color color) @safe nothrow {
            	this.color_ = color;
            
            	return this;
            }
            
            Color color() @safe nothrow {
            	return this.color_;
            }
            
            Size size() @safe nothrow {
            	return this.size_;
            }
            
            /**
            Set engine used in car.
            
            Params:
            	engine = engine used in car to propel it.
            
            Returns:
            	Car
            **/
            Car engine(Engine engine) @safe nothrow {
            	this.engine_ = engine;
            
            	return this;
            }
            
            Engine engine() @safe nothrow {
            	return this.engine_;
            }
            
            Car frontLeft(Tire frontLeft) @safe nothrow {
            	this.frontLeft_ = frontLeft;
            
            	return this;
            }
            
            Tire frontLeft() @safe nothrow {
            	return this.frontLeft_;
            }
            
            Car frontRight(Tire frontRight) @safe nothrow {
            	this.frontRight_ = frontRight;
            
            	return this;
            }
            
            Tire frontRight() @safe nothrow {
            	return this.frontRight_;
            }
            
            Car backLeft(Tire backLeft) @safe nothrow {
            	this.backLeft_ = backLeft;
            
            	return this;
            }
            
            Tire backLeft() @safe nothrow {
            	return this.backLeft_;
            }
            
            Car backRight(Tire backRight) @safe nothrow {
            	this.backRight_ = backRight;
            
            	return this;
            }
            
            Tire backRight() @safe nothrow {
            	return this.backRight_;
            }
            
        }
        
        void start() {
            engine.turnOn();
        }
        
        void run() {
            engine.run();
        }
        
        void stop() {
            engine.turnOff();
        }
    }
}

void drive(Car car, string name) {
    writeln("Uuh, what a nice car, ", name," with following specs:");
    writeln("Size:\t", car.size());
    writeln("Color:\t", car.color());
    writeln("Engine:\t", car.engine());
    writeln("Tire front left:\t", car.frontLeft(), "\t located at memory ", cast(void*) car.frontLeft());
    writeln("Tire front right:\t", car.frontRight(), "\t located at memory ", cast(void*) car.frontRight());
    writeln("Tire back left: \t", car.backLeft(), "\t located at memory ", cast(void*) car.backLeft());
    writeln("Tire back right:\t", car.backRight(), "\t located at memory ", cast(void*) car.backRight());
}

auto configContainer() {
	auto configContainer = container(
		argument(),
		environment(),
        xml("config-primary.xml"),
		xml("config.xml"),
		json("config.json")
	);

	foreach (c; configContainer.containers) {
		with (c.configure) {

			property!string("profile");
			property!string("tire");            
			property!int("tire_size");
			property!float("tire_pressure");
		}
	}

	return configContainer;
}

auto containerWithProfiles() {
    auto container = new ApplicationContainer; // A composite container with singleton, prototype built in.
    
    auto electricProfileContainer = singleton.switchable(); // creating a singleton, and decorating it with switchable container
    auto gasolineProfileContainer = singleton.switchable(); // creating a singleton, and decorating it with switchable container
    auto dieselProfileContainer = singleton.switchable(); // creating a singleton, and decorating it with switchable container
    auto subscribableContainer = container.subscribable(); // decorating joint container with subscribable container
    
    container.set(electricProfileContainer, "electric");
    container.set(gasolineProfileContainer, "gasoline");
    container.set(dieselProfileContainer, "diesel");
    
    subscribableContainer.subscribe(
        ContainerInstantiationEventType.pre,
        {
			if (container.has(container.locate!string("profile"))) {
				try {
					
					container.locate!Switchable(container.locate!string("profile")).enabled = true;
				} catch (InvalidCastException e) {
					
				}
			}
        }
    );
    
    return subscribableContainer;
}

void main(string[] args) {
    
    auto container = containerWithProfiles();
	container.decorated.set(configContainer(), "configuration");

    with (container.configure("singleton")) {
        register!Color; // Let's register a default implementation of Color
        
        register!Size // Let's register default implementation of a Size
            .set!"width"(200UL) 
            .set!"height"(150UL)
            .set!"length"(300UL);
        
        register!Car
            .autowire
            .autowire!"color"
            .set!"frontLeft"(lref!Tire)
            .set!"frontRight"(lref!Tire)
            .set!"backLeft"(lref!Tire)
            .set!"backRight"(lref!Tire);
    }

    with (container.configure("prototype")) {
        register!Tire
            .set!"size"("tire_size".lref)
            .set!"pressure"("tire_pressure".lref)
            .set!"vendor"("tire".lref);
    }

    with (container.configure("diesel")) {
        register!(Engine, DieselEngine);
    }

    with (container.configure("gasoline")) {
        register!(Engine, GasolineEngine);
    }

    with (container.configure("electric")) {
        register!(Engine, ElectricEngine);
    }
    
    container.instantiate();
    
    container.locate!Car.drive("");
}