/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module app;

import aermicioi.aedi;
import aermicioi.aedi_property_reader;
import std.stdio;
import std.algorithm;
import std.experimental.allocator;
import std.conv;

@component
class Car {
    @setter("car.color".lref)
    Color color;

    @setter("car.size".lref)
    Size size;

    @setter("car.weight".lref)
    double weight;

    @callback((Locator!() locator, ref Car component) {
        component.doors = [
            locator.locate!Door("car.door.front.left"),
            locator.locate!Door("car.door.front.right"),
            locator.locate!Door("car.door.back.left"),
            locator.locate!Door("car.door.back.right"),
        ];
    })
    Door[] doors;

    @callback((Locator!() locator, ref Car component) {
        component.tires = [
            locator.locate!Tire,
            locator.locate!Tire,
            locator.locate!Tire,
            locator.locate!Tire,
        ];
    })
    Tire[] tires;

    @autowired
    Engine engine;

    @setter("car.vendor".lref)
    string vendor;

    override string toString() {return text("Car(", color, ", ", size, ", ", doors, ", ", tires, ", ", weight, ", ", engine, ", ", vendor, ")");}
}

class Door {
    enum Locking {
        manual,
        automatic
    }

    Window window;

    Locking locking;

    string position;

    override string toString() {return text("Door(", window, ", ", locking, ", ", position, ")");}
}

class Window {

    Size size;
    double transparency;
    Color color;

    override string toString() {return text("Window(", size, ", ", transparency, ", ", color, ")");}
}

class Tire {
    double pressure;
    double size;
    string vendor;

    override string toString() {return text("Tire(", pressure, ", ", size, ", ", vendor, ")");}
}

struct Color {
    ubyte r;
    ubyte g;
    ubyte b;
}

struct Size {

    long width;
    long height;
    long length;
}

/**
Interface for engines.

An engine should implement it, in order to be installable in a car.
**/
interface Engine {

    public {

        void run();
    }
}

/**
A concrete implementation of Engine that uses gasoline for propelling.
**/
class GasolineEngine : Engine {

    public {

        void run() {
            writeln("Gasoline engine running sound...");
        }
    }
}

/**
A concrete implementation of Engine that uses diesel for propelling.
**/
class DieselEngine : Engine {

    public {

        void run() {
            writeln("Diesel engine running sound...");
        }
    }
}

/**
A concrete implementation of Engine that uses electricity for propelling.
**/
class ElectricEngine : Engine {
    public {

        void run() {
            writeln("Electric engine running sound...");
        }
    }
}

void drive(Car car, string name) {

}

void main(string[] args) {

    auto c = container(
        singleton,
        prototype,
        argument,
        env,
        properd("car.properties"),
        xml("car.xml"),
        json("car.json"),
        sdlang("car.sdlang"),
        yaml("car.yaml")
    );

    foreach (subcontainer; c[2 .. 5]) {
        with (subcontainer.configure) {
            register!string("car.vendor");
            register!double("car.weight");
            register!ubyte("car.color.r");
            register!ubyte("car.color.g");
            register!ubyte("car.color.b");
        }
    }

    foreach (subcontainer; c[5 .. $]) {
        with (subcontainer.configure) {
            register!string;
            register!long;
            register!double;
            register!ubyte;
            register!Door("car.door.front.left");
            register!Door("car.door.front.right");
            register!Door("car.door.back.left");
            register!Door("car.door.back.right");
            register!Window;
            register!Size("car.size");
            register!Color("car.color");
            register!(Door.Locking);
        }
    }

    with (c[0].configure(c)) {
        c[0].scan!app(c);

        register!(Engine, ElectricEngine);
        register!Color("car.color")
            .set!"r"("car.color.r".lref)
            .set!"g"("car.color.g".lref)
            .set!"b"("car.color.b".lref);
    }

    with(c[1].configure) {
        register!Tire
            .set!"pressure"(1.0)
            .set!"size"(17)
            .set!"vendor"("good.tire");
    }

    c.locate!Car.writeln;
}