/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi_property_reader.sdlang.convertor;

import aermicioi.aedi_property_reader.core.convertor;
import aermicioi.aedi_property_reader.core.inspector;
import aermicioi.aedi_property_reader.core.accessor;
import aermicioi.aedi_property_reader.sdlang.inspector;
import aermicioi.aedi.exception.invalid_cast_exception : InvalidCastException;
import aermicioi.aedi_property_reader.sdlang.accessor : SdlangElement;
import sdlang.ast;
import sdlang;
import std.conv;
import std.traits;
import std.meta;
import std.experimental.allocator;

public {
	import aermicioi.aedi_property_reader.sdlang.sdlang : accessor;
	enum SdlangAccessorFactory(From : SdlangElement) = () => new RuntimeFieldAccessor!SdlangElement(accessor());
	enum SdlangInspectorFactory(From : SdlangElement) = () => new TaggedInspector!(SdlangElement, Tag)(new SdlangTagInspector);
}

alias SdlangConvertorBuilderFactory = (Convertor[] convertors) {
	return factoryAnyConvertorBuilder(
		new CallbackConvertorBuilder!(convert, destruct),
		new MappingConvertorBuilder!(
			SdlangAccessorFactory,
			CompositeSetterFactory,
			CompositeInspectorFactory,
			SdlangInspectorFactory
		)(convertors, true, true, true, true)
	);
};

void convert(To, From : Tag)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && !isNumeric!To && !isSomeChar!To && !isSomeString!To) {
	try {

		to = (cast() from).expectValue!To;
	} catch (ValueNotFoundException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To, From : Tag)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isNumeric!To && isFloatingPoint!To) {
	try {

		static if (is(typeof((cast() from).expectValue!To))) {

			to = (cast() from).expectValue!To;
		} else {

			static foreach(Numeric; AliasSeq!(real, double, float)) {
				foreach (value; (cast() from).values) {
					if (value.type is typeid(Numeric)) {
						to = (cast() from).expectValue!Numeric.to!To;
						return;
					}
				}
			}

			throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"));
		}
	} catch (ValueNotFoundException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"), e);
	}
}

void convert(To, From : Tag)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isNumeric!To && !isFloatingPoint!To) {
	try {

		static if (is(typeof((cast() from).expectValue!To))) {

			to = (cast() from).expectValue!To;
		} else {

			static foreach(Numeric; AliasSeq!(long, int)) {
				foreach (value; (cast() from).values) {
					if (value.type is typeid(Numeric)) {
						to = (cast() from).expectValue!Numeric.to!To;
						return;
					}
				}
			}

			throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"));
		}
	} catch (ValueNotFoundException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"), e);
	}
}

void convert(To : E[], From : Tag, E)(in From from, ref To to, RCIAllocator allocator = theAllocator)
	if (!is(To == enum) && !is(To : ubyte[]) && !isSomeString!To) {

	import std.variant;
	to = allocator.makeArray!E(from.values.length);

	foreach (index, ref value; to) {
		try {

			value = from.values[index].get!E;
		} catch (VariantException e) {

			throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value ", e));
		}
	}
}

void convert(To, From : Tag)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isSomeChar!To) {

	try {

		to = (cast() from).expectValue!string.to!To;
	} catch (ValueNotFoundException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To : T[], From : Tag, T)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isSomeChar!T) {

	try {

		to = (cast() from).expectValue!string.to!To;
	} catch (ValueNotFoundException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To, From : Attribute)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && !isNumeric!To && !isSomeChar!To) {
	import std.variant : VariantException;

	try {
		to = cast(To) from.value.get!To;

	} catch (VariantException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To : T[], From : Attribute, T)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isSomeChar!T) {
	import std.variant : VariantException;

	try {
		to = cast(To) from.value.get!string.to!To;

	} catch (VariantException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To, From : Attribute)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && !isNumeric!To && isSomeChar!To) {
	import std.variant : VariantException;

	try {
		to = cast(To) from.value.get!string.to!To;

	} catch (VariantException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To, From : Attribute)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isNumeric!To && isFloatingPoint!To) {
	import std.variant : VariantException;

	try {
		static foreach (Numeric; AliasSeq!(real, double, float)) {
			if (from.value.type is typeid(Numeric)) {

				to = cast(To) from.value.get!Numeric.to!To;
				return;
			}
		}

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"));
	} catch (VariantException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value", e));
	}
}

void convert(To, From : Attribute)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (!is(To == enum) && isNumeric!To && !isFloatingPoint!To) {
	import std.variant : VariantException;

	try {
		static foreach (Numeric; AliasSeq!(long, int)) {
			if (from.value.type is typeid(Numeric)) {

				to = cast(To) from.value.get!Numeric.to!To;
				return;
			}
		}

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"));
	} catch (VariantException e) {

		throw new InvalidCastException(text("Could not convert value to requested ", typeid(To), " value"), e);
	}
}

void convert(To, From : Tag)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (is(To == enum)) {
	string temp;
    from.convert!string(temp, allocator);
    to = temp.to!To;
	temp.destruct(allocator);
}

void convert(To, From : Attribute)(in From from, ref To to, RCIAllocator allocator = theAllocator) if (is(To == enum)) {
	string temp;
    from.convert!string(temp, allocator);
    to = temp.to!To;
	temp.destruct(allocator);
}

void convert(To, From : SdlangElement)(in From from, ref To to, RCIAllocator allocator = theAllocator) {

	final switch (from.kind) {
		case SdlangElement.Kind.tag: {
			(cast(const(Tag)) from).convert(to, allocator);
			return;
		}

		case SdlangElement.Kind.attribute: {
			(cast(const(Attribute)) from).convert(to, allocator);
			return;
		}
	}
}

void destruct(To)(ref To to, RCIAllocator allocator = theAllocator) {

	destroy(to);
	to = To.init;
}